backend:
  name: github
  repo: Aaronjoshuachua/autumn-static

media_folder: "/static/files/images"
public_folder: "/files/images"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about/about.md"
        fields:
          - {label: "Content Type", name: "contentType", widget: "hidden", default: "about"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Members"
            name: "members"
            widget: "list"
            fields:
              - {label: "Photo", name: "photo", widget: "image" }
              - {label: "Fullname", name: "fullname", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Quote", name: "bio", widget: "string"}
  - label: "News"
    name: "news"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "news"}
      - label: "Path"
        name: "path"
        widget: "string"
        default: "/news/"
        pattern: ["/news/", "add a /news/ prefix to your path"]
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - label: "PostImage"
        name: "postimage" 
        widget: "file"
        hint: "make sure you have a news- prefix for your image"
        pattern: ["(news-)(.*[.])", "must have news- prefrex"]
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - {label: "Tag", name: "name", widget: "string" }
  - label: "Careers"
    name: "careers"
    folder: "content/careers"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "careers"}
      - label: "Path"
        name: "path"
        widget: "string"
        default: "/careers/"
        pattern: ["/careers/", "add a /careers/ prefix to your path"]
      - {label: "Title", name: "title", widget: "string"}
      - label: "Job Type"
        name: "jobtype"
        widget: "select"
        options: ["developer", "art", "designer", "marketing"]
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Body"
        name: "body"
        widget: "markdown"