backend:
  name: github
  repo: Aaronjoshuachua/autumn-static

media_folder: "/static/files/images"
public_folder: "/files/images"

collections:
  - label: "News"
    name: "news"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "news"}
      - {label: "Path", name: "path", widget: "string", default: "/news/"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "PostImage", name: "postimage", widget: "file"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Tags
        name: tags
        widget: list
        fields:
          - {label: Tag, name: name, widget: string }